### ISSUE TITLE
Skipping ahead breaks audio?

### ISSUE THREAD

**Issue by RobertLowe** [scrimba/community#213] opened 2018-01-09 00:33 UTC
Hi,

When skipping ahead on: https://scrimba.com/casts/cast-1980 audio breaks in Chrome (63.0.3239.84 (Official Build) (64-bit)) / Mac OS X 10.13.1 I was able to reproduce the issue in Safari & Firefox. The cast was playing fine before skipping from the beginning.

Conversely I'm able to skip able on: https://scrimba.com/p/pRB9Hw/cJL9dAJ or https://scrimba.com/c/c36zkcb - so it appears limited to https://scrimba.com/casts/cast-1980

@perborgen thanks for the casts by the way, hope this report helps.

**Comment by somebee** [comment] 2018-01-09 18:32
We've fixed a ton of things in our audio creation since this cast was first published. I tried republishing it now, and that seemed to help. Can you still reproduce it?

**Comment by RobertLowe** [comment] 2018-01-09 19:50
@somebee cannot reproduce it, re-publishing fixed the issue!! Thanks.

May consider republishing older casts on mass? :)

Happy hacking 👍

**Comment by somebee** [comment] 2018-01-10 06:08
We should, yes :) Thanks for the report. Closing issue!

**Closed by somebee** 2018-01-10 06:08 UTC
