### ISSUE TITLE
Search for "vue" doesn't show vue.js casts

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#138] opened 2017-11-13 11:30 UTC

**Comment by judofyr** [comment] 2017-11-13 12:59
This is caused by parser treating "vue.js" as a hostname. We probably need to preprocess the data before we index it. I'll look into it.

**Comment by judofyr** [comment] 2017-11-14 07:44
I'm going to solve this together with a more robust indexing solution:

- [ ] Add separate full-text-search column (with index) on the `spaces`-table
- [ ] Create function for preprocessing text
- [ ] Create trigger to automatically update the index

**Comment by perborgen** [comment] 2017-11-15 07:59
@judofyr searching for "ramda" gives 0 results as well, even though there are a couple of casts on the subject, e.g.:

https://scrimba.com/casts/cnb2fJ

Will this be solved by any of the changes above?

**Comment by judofyr** [comment] 2017-11-15 11:00
Yes, it's fixed now: https://scrimba.com/search?q=ramda

**Closed by judofyr** 2017-11-15 11:00 UTC
