### ISSUE TITLE
Running the example when recording breaks the browser window 

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#152] opened 2017-11-22 11:11 UTC
The browser keeps on refreshing again and again forever when I run the example in this cast (while recording):

https://scrimba.com:9100/c/crb8wf8

However, it doesn't happen if I do it when in 'notes'.

**Comment by somebee** [comment] 2017-12-01 10:14
I think this was caused by a pointer-regression which is now fixed. Please reopen if you run into this again.

**Closed by somebee** 2017-12-01 10:14 UTC
Labels: bug
