### ISSUE TITLE
NPM package not working: contentful

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#120] opened 2017-10-12 03:21 UTC
import * as contentful from 'contentful'

will give the following error:

SyntaxError: Unexpected token import

Check out this cast:

https://scrimba.com/c/c4rbpSa

**Comment by judofyr** [comment] 2017-10-12 05:25
Doesn't use `index.pack.js`. Dupe of #81.

**Closed by judofyr** 2017-10-12 05:25 UTC
Labels: bug
