### ISSUE TITLE
Website refresh causing loss of work

### ISSUE THREAD

**Issue by rokublac** [scrimba/community#431] opened 2019-07-23 08:47 UTC
Opening an issue on behalf of @regurii. Initial issue was posted in the community chat - the post can be found [here](https://spectrum.chat/scrimba/general/lost-all-progress~26a4d4bc-b140-4557-a3ea-68e4e27f9de5).

User had Scrimba opened on two different devices (PC and laptop) while also being logged in on the same account. They initially created a playground on their PC but then continued coding on their laptop. When they returned to their PC, their playground code was not the latest version even though they have been updating their code on their laptop.

If you are logged in on multiple devices, generally, Scrimba editor activity would be consistent since the user is essentially sharing the same work space, thus, all updates will be reflected to all devices. But in this case, there were some inconsistencies (only some updates were in place).

We suspect that it could be due to the browser state after returning from sleep mode (or some other inactive mode) which automatically triggers a browser refresh causing this inconsistency. Along with the simultaneous activity on different devices, this might cause some weird behavior.

I was not able to recreate this particular issue, so I'm not too sure what the problem is.

**Comment by Pistus** [comment] 2020-04-02 07:31
I believe this issue should be fixed with the introduction of service workers for the workspaces - as the state is not shared anymore. There is still a reload if the session has disconnected from the websocket, but that should not cause changes. I think this issue can be closed @scanf as it also can´t be reproduced.

**Comment by scanf** [comment] 2020-04-02 07:58
I am little bit hesitant to close this. Let me take a closer look and make sure I can't reproduce.



Thanks.

**Comment by scanf** [comment] 2020-04-16 09:05
Tried reproducing it but suspect this has been resolved. Please reopen if that is not the case.

Thanks.

**Closed by scanf** 2020-04-16 09:05 UTC
